# menu
menu:
  Home: .
  Archives: archives  # å½’æ¡£
  Categories: categories  # åˆ†ç±»
  Tags: tags  # æ ‡ç­¾
  Repository: repository  # github repositories
  #Books: books  # è±†ç“£ä¹¦å•
  Links: links  # å‹é“¾
  About: about  # å…³äº

# Enable/Disable menu icons
menu_icons:
  enable: true  # æ˜¯å¦å¯ç”¨å¯¼èˆªèœå•å›¾æ ‡
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  #books: icon-book-fill
  links: icon-friendship
  about: icon-cup-fill

# rss
rss: /atom.xml

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/logo.png
  title: ğš²ğš³ğš²çš„åšå®¢ # é¡µé¢title
  favicon: ../favicon.ico
  board: <p>æ¬¢è¿äº¤æµä¸åˆ†äº«ç»éªŒ!</p> # ç«™ç‚¹å…¬å‘Š
  copyright: true # åº•éƒ¨ç‰ˆæƒä¿¡æ¯

# config
config:
  skin: theme-white # ä¸»é¢˜é¢œè‰² theme-white theme-black theme-blue theme-green theme-purple
  layout: main-center # å¸ƒå±€æ–¹å¼ main-left main-center main-right
  toc: true # æ˜¯å¦å¼€å¯æ–‡ç« ç« èŠ‚ç›®å½•å¯¼èˆª
  menu_highlight: false # æ˜¯å¦å¼€å¯å½“å‰èœå•é«˜äº®æ˜¾ç¤º
  thumbnail: false # ç¼©ç•¥å›¾ ï¼Œenable posts thumbnail, options: true, false
  excerpt_link: Read More
  #New
  isNewTabLinks: false #æ˜¯å¦é“¾æ¥æ‰“å¼€æ–°æ ‡ç­¾é¡µ
  autoUnfold: true # é»˜è®¤å±•å¼€æ–‡ç« ç›®å½•

# Pagination
pagination:
  number: true
  prev: 
    alwayShow: true
  next:
    alwayShow: true
  midSize: 2 # å½“å‰é¡µç å·¦å³åˆ°çœç•¥å·æ˜¾ç¤ºçš„é¡µç æ•°ï¼Œé»˜è®¤2ï¼Œè¡¨ç°ä¸º 1 ... 4 5 6 7 8 ... 10
  showContent: true # é¡µé¢æ–‡ç« å°äº2ç¯‡æ—¶æ˜¾ç¤ºæ–‡ç« å†…å®¹

# Sidebar  é¡µé¢å³ä¾§æ ç›®è®¾ç½®
sidebar: right
widgets:
  - board  
  - category
  - tag
  # - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# widget behavior
archive_type: 'monthly'
show_count: true

# Fancybox
fancybox: false

# Search
search:
  insight: true # å†…ç½®æœç´¢åŠŸèƒ½
  baidu: false # ç™¾åº¦æœç´¢åŠŸèƒ½,ä¸å¯ä»¥åŒæ—¶ä½¿ç”¨

# Donate
donate:
  enable: true
  # å¾®ä¿¡æ‰“èµ
  wechatpay:
    qrcode: images/donate/wechatpayimg.png # åœ¨ä¸»é¢˜ç›®å½•çš„sourceæ–‡ä»¶å¤¹ä¸­è¿›è¡Œå›¾ç‰‡çš„è®¾å®š
    title: å¾®ä¿¡æ”¯ä»˜
  # æ”¯ä»˜å®æ‰“èµ
  alipay: 
    qrcode: images/donate/alipayimg.png # åœ¨ä¸»é¢˜ç›®å½•çš„sourceæ–‡ä»¶å¤¹ä¸­è¿›è¡Œå›¾ç‰‡çš„è®¾å®š
    title: æ”¯ä»˜å®

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: false   # trueæ˜¯å¦å¯ç”¨åˆ†äº«
  sites: weibo,qq,wechat,facebook,twitter  # PCç«¯æ˜¾ç¤ºçš„åˆ†äº«å›¾æ ‡
  mobile_sites: weibo,qq,qzone  # ç§»åŠ¨ç«¯æ˜¾ç¤ºçš„åˆ†äº«å›¾æ ‡

# Github
# github: 
#   username: cofess  # github username

# Repository Info (This will override 'github' option)
# é¡¹ç›®ä»“åº“ä¿¡æ¯ï¼ˆå°†ä¼šè¦†ç›– github é¡¹ï¼‰
repository:
  platform: gitee # æ‰˜ç®¡å¹³å°ï¼ˆgithub | giteeï¼‰
  username: lmlpla # ç”¨æˆ·å

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  # type: valine  # å¯ç”¨å“ªç§è¯„è®ºç³»ç»Ÿ
  # disqus:  # enter disqus shortname here
  # youyan: 
  #   uid: 1783844 # enter youyan uid 
  # livere:
  #   uid: # enter youyan uid 
  # gitment:
  #   githubID: 
  #   repo: 
  #   ClientID: 
  #   ClientSecret: 
  #   lazy: false
  gitalk: # gitalk. https://gitalk.github.io/
    owner:  #å¿…é¡». GitHub repository æ‰€æœ‰è€…ï¼Œå¯ä»¥æ˜¯ä¸ªäººæˆ–è€…ç»„ç»‡ã€‚
    admin:  #å¿…é¡». GitHub repository çš„æ‰€æœ‰è€…å’Œåˆä½œè€… (å¯¹è¿™ä¸ª repository æœ‰å†™æƒé™çš„ç”¨æˆ·)ã€‚
    repo:  #å¿…é¡». GitHub repository.
    ClientID:  #å¿…é¡». GitHub Application Client ID.
    ClientSecret:  #å¿…é¡». GitHub Application Client Secret.
    enableHotKey: true
    language: zh-CN
    
#   valine: # Valine. https://valine.js.org
#     appid:  # your leancloud application appid
#     appkey:  # your leancloud application appkey
#     notify: false # mail notifier , https://github.com/xCss/Valine/wiki
#     verify: false # Verification code
#     placeholder: Just go go # comment box placeholder
#     avatar: mm # gravatar style
#     meta: nick,mail,link # custom comment header
#     pageSize: 10 # pagination size
#     visitor: false # Article reading statistic https://valine.js.org/visitor.html

# douban è±†ç“£ä¹¦å•
# Apiï¼š
  # https://developers.douban.com/wiki/?title=book_v2 å›¾ä¹¦
  # https://developers.douban.com/wiki/?title=movie_v2 ç”µå½±
# booksï¼š  
  # https://api.douban.com/v2/book/user/:name/collections?start=0&count=100 ä¸ªäººä¹¦å•åˆ—è¡¨
# movies: 
  # https://api.douban.com/v2/movie/in_theaters æ­£åœ¨ä¸Šæ˜ çš„ç”µå½±
  # https://api.douban.com/v2/movie/coming_soon å³å°†ä¸Šæ˜ çš„ç”µå½±
  # https://api.douban.com/v2/movie/subject/:id å•ä¸ªç”µå½±ä¿¡æ¯
  # https://api.douban.com/v2/movie/search?q={text} ç”µå½±æœç´¢
douban:
  user: # è±†ç“£ç”¨æˆ·å
  start: 0 # ä»å“ªä¸€æ¡è®°å½•å¼€å§‹
  count: 100 # è·å–è±†ç“£ä¹¦å•æ•°æ®æ¡æ•°
  apikey: # è±†ç“£apikey
  
# PV
pv: # æµè§ˆé‡ç»Ÿè®¡
  busuanzi:
    enable: false  # ä¸è’œå­ç»Ÿè®¡ï¼Œä¸€èˆ¬ä½¿ç”¨ä¸è’œå­ç»Ÿè®¡ï¼Œä½¿ç”¨trueå¼€å¯
  leancloud:
    enable: false  # leancloudç»Ÿè®¡
    app_id: # leancloud <AppID>
    app_key: # leancloud <AppKey>
        
# wordcount
postCount:
  enable: true
  wordcount: true  # æ–‡ç« å­—æ•°ç»Ÿè®¡
  min2read: true  # é˜…è¯»æ—¶é•¿é¢„è®¡ 

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  tencent_analytics: 
  
# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:  
  
# profile
profile:
  enabled: true # Whether to show profile bar
  articleSelfBlock: false # å…³é—­æ–‡ç« ä¸‹æ–¹çš„è‡ªæˆ‘ä»‹ç»
  avatar: images/avatar.jpg
  gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: ğš²ğš³ğš² #ğ“µğ“¶ğ“µ
  author_title: â—™
  author_description: ä¸šç²¾äºå‹¤ï¼Œè’äºå¬‰ï¼›è¡Œæˆäºæ€ï¼Œæ¯äºéšï¼
  location: Shenzhen, China
  follow: 
  # Social Links  å·¦ä¸‹è§’é“¾æ¥
  social:
    links:
      # gitee: https://gitee.com/lmlpla
      github: https://github.com/protonlml
      #weibo: http://weibo.com/cofess
      #twitter: https://twitter.com/iwebued
      # facebook: /
      # dribbble: /
      #behance: https://www.behance.net/cofess
      rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills å…³äº é¡µé¢çš„å³ä¾§æ ç›®
  skills:
    Git: â˜…â˜…â˜†â˜†â˜†
    Java: â˜…â˜…â˜…â˜†â˜†
    Javascript: â˜…â˜†â˜†â˜†â˜†
    Vue: â˜…â˜…â˜†â˜†â˜†
    #HTML+CSS: â˜…â˜…â˜…â˜†â˜†
    #Bootstrap: â˜…â˜…â˜…â˜†â˜†
    #ThinkPHP: â˜…â˜…â˜…â˜†â˜†
    #å¹³é¢è®¾è®¡: â˜…â˜…â˜…â˜†â˜†
  # My Personal Links
  links:
    # Gitee: https://gitee.com/lmlpla
    GitHub: https://github.com/protonlml
    Blog: https://protonlml.github.io
    #å¾®åš: http://weibo.com/cofess
    #èŠ±ç“£: http://huaban.com/cofess
    #Behance: https://www.behance.net/cofess
  # My Personal Labels
  labels:
    - éŸ³ä¹è¡—èˆ
    - æ‘„å½±ç”Ÿæ´»
    - 
    - 
    - 
  # My Personal Works
  #works:
  # name:
  #   link: http://www.example.com
  #    date: 2016
  # My Personal Projects
  #projects:
   # cofess/gulp-startpro: https://github.com/cofess/gulp-startpro
    #cofess/hexo-theme-pure: https://github.com/cofess/hexo-theme-pure

# Some suprise plugs   # è¸¢çš®çƒåŠ¨ç”»å¼€å…³
suprise:
  ball_enable: true